import "./StepsBanner.css";
import searchIcon from "../../../assets/images/icons/search.svg";
import selectIcon from "../../../assets/images/icons/select.svg";
import standoutIcon from "../../../assets/images/icons/standout.svg";

const StepsBanner = () => {
  return (
    <section className="steps__banner">
      <div className="steps-banner__step">
        <div className="steps-banner__step-main">
          <img
            src={searchIcon}
            alt="search"
            className="step-banner__step-main__icon"
          />
          <span className="step-banner__step-main__title">Search</span>
        </div>
        <p className="steps-banner__step-main__desc">
          Simply add a keyword or a term related to your business in the slogan
          maker search box. Wait for the magic to happen.
        </p>
      </div>

      <div className="steps-banner__step">
        <div className="steps-banner__step-main">
          <img
            src={selectIcon}
            alt="select"
            className="step-banner__step-main__icon"
          />
          <span className="step-banner__step-main__title">Select</span>
        </div>
        <p className="steps-banner__step-main__desc">
          Choose from thousands of options generated by the slogan maker that
          fit your needs.
        </p>
      </div>

      <div className="steps-banner__step">
        <div className="steps-banner__step-main">
          <img
            src={standoutIcon}
            alt="standout"
            className="step-banner__step-main__icon"
          />
          <span className="step-banner__step-main__title">Stand out</span>
        </div>
        <p className="steps-banner__step-main__desc">
          Congrats on your new slogan. It's time to win the world!
        </p>
      </div>
    </section>
  );
};

export { StepsBanner };
